server:
  port: 8761

spring:
  application:
    name: eueka-server

eureka:
  client:
    #当前这个Eureka Server不能自己注册给自己
    register-with-eureka: false
    # 当前这个Eureka Server不去别的Eureka Server拉取注册表
    fetch-registry: false